global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Maui;
global using Microsoft.Maui.Controls;
global using Microsoft.Maui.Hosting;
global using StaffContactDirectory.Database;
global using StaffContactDirectory.Model;
global using StaffContactDirectory.Service;
global using StaffContactDirectory.View;
global using StaffContactDirectory.ViewModel;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Linq;
global using System.Threading.Tasks;
global using AppInfo = Microsoft.Maui.ApplicationModel.AppInfo;
global using CommunityToolkit.Mvvm.DependencyInjection;
global using System.Windows.Input;
//global using Android.Content.PM;
//global using Android.Runtime;
global using Microsoft.Maui.ApplicationModel;

global using SQLite;
global using PrimaryKeyAttribute = SQLite.PrimaryKeyAttribute;
global using System.ComponentModel.DataAnnotations.Schema;
global using TableAttribute = SQLite.TableAttribute;

